# FindTargetOrder.action

# Goal
string target_name
---
# Result 
bool found
float64[3] coordinate       # 로봇 베이스 좌표계 기준 [x, y, z] -> "이건 로봇이 이동할 때 사용"
string message # class 
---
# Feedback
string state 
